# Generated by Django 4.2.2 on 2023-09-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_date',
        ),
        migrations.AddField(
            model_name='event',
            name='ecity',
            field=models.TextField(default=''),
        ),
    ]
