# Generated by Django 4.2.2 on 2023-09-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_event_created_date_event_ecity'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ezip',
            field=models.CharField(default='', max_length=10),
        ),
    ]
