# Generated by Django 4.2.2 on 2023-09-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_event_ezip'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eaddress',
            field=models.TextField(default=''),
        ),
    ]
