# Generated by Django 4.2.2 on 2023-09-09 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_event_eaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='img/eventdefault.png', upload_to='event_image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='edate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='img/profile.png', upload_to='profile_image'),
        ),
    ]
