# Generated by Django 4.2.2 on 2023-09-13 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_event_event_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_id',
            new_name='eventid',
        ),
    ]
