# Generated by Django 4.2.2 on 2023-09-13 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_rename_event_id_event_eventid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='eventid',
            new_name='event_id',
        ),
    ]
